//! TypeScript emitted from Rust, so a TS mirror of a Rust type or value is
//! generated instead of re-typed. A repo builds a `Vec<Ts>` per module in its
//! own `gen` binary and [`Ts::write`]s it; the output is committed.
//!
//! ```ignore
//! Ts::write(&root.join("frontend/src/generated.ts"), &[
//!     Ts::types::<Caller>(),
//!     Ts::Value { name: "ROLES", value: serde_json::to_value(Role::iter().collect::<Vec<_>>()).unwrap() },
//! ]);
//! ```

use std::{collections::BTreeMap, fmt::Write as _, fs, path::Path};

use serde_json::Value;
use ts_rs::{Config, TS, TypeVisitor};

/// One TS export.
#[derive(Debug)]
pub enum Ts {
	/// `export const NAME = "value";`
	Const { name: &'static str, value: &'static str },
	/// `export const NAME = <literal>;`, an array or object `as const`. Built from
	/// the Rust value through serde, so its keys and words are the wire's.
	Value { name: &'static str, value: Value },
	/// `export const NAME = ["a", …] as const;` and
	/// `export type TY = (typeof NAME)[number];`: a closed set of words.
	Union { name: &'static str, ty: &'static str, items: Vec<&'static str> },
	/// `export const NAME = { "key": "value", … } as const;` and
	/// `export type TY = keyof typeof NAME;`
	Table {
		name: &'static str,
		ty: &'static str,
		entries: Vec<(String, String)>,
	},
	/// Declarations rendered by [`Ts::types`], by name: `ts-rs` visits a type's
	/// dependencies in no fixed order.
	Types(BTreeMap<String, String>),
}

impl Ts {
	/// `T` and every type it names, declared as serde writes them (`ts-rs` reads the
	/// serde attributes). Several roots are a tuple, `(A, B)`, so a type both name
	/// is declared once.
	pub fn types<T: TS + 'static>() -> Self {
		struct Decls {
			cfg: Config,
			out: BTreeMap<String, String>,
		}
		impl TypeVisitor for Decls {
			fn visit<T: TS + 'static + ?Sized>(&mut self) {
				// Only a derived type has a file of its own; a primitive or a wrapper is inlined.
				if T::output_path().is_some() {
					let name = T::ident(&self.cfg);
					if self.out.contains_key(&name) {
						return;
					}
					self.out.insert(name, format!("{}export {}", T::docs().unwrap_or_default(), T::decl(&self.cfg)));
				}
				T::visit_dependencies(self);
				T::visit_generics(self);
			}
		}
		let mut decls = Decls {
			cfg: Config::default(),
			out: BTreeMap::new(),
		};
		decls.visit::<T>();
		assert!(!decls.out.is_empty(), "{} declares no type", T::name(&decls.cfg));
		Ts::Types(decls.out)
	}

	/// One generated module. The header names `nix run .#gen`, which every repo
	/// using this exposes as its one way to regenerate.
	pub fn write(path: &Path, exports: &[Ts]) {
		let mut out = String::from("// AUTO-GENERATED by `nix run .#gen` — do not edit.\n\n");
		for (i, ts) in exports.iter().enumerate() {
			if i > 0 {
				out.push('\n');
			}
			ts.render(&mut out);
		}
		fs::create_dir_all(path.parent().expect("a module is a file in a directory")).expect("create the module's directory");
		fs::write(path, out).expect("write generated module");
		println!("wrote {}", path.display());
	}

	fn render(&self, out: &mut String) {
		match self {
			// The `{:?}` Debug formatting doubles as a TS string-literal quoter.
			Ts::Const { name, value } => writeln!(out, "export const {name} = {value:?};").unwrap(),
			Ts::Value { name, value: Value::Object(fields) } => {
				writeln!(out, "export const {name} = {{").unwrap();
				for (key, v) in fields {
					writeln!(out, "  {key:?}: {},", literal(v)).unwrap();
				}
				out.push_str("} as const;\n");
			}
			Ts::Value { name, value: v @ Value::Array(_) } => writeln!(out, "export const {name} = {} as const;", literal(v)).unwrap(),
			Ts::Value { name, value } => writeln!(out, "export const {name} = {};", literal(value)).unwrap(),
			Ts::Union { name, ty, items } => {
				writeln!(out, "export const {name} = {:?} as const;", items).unwrap();
				writeln!(out, "export type {ty} = (typeof {name})[number];").unwrap();
			}
			Ts::Table { name, ty, entries } => {
				writeln!(out, "export const {name} = {{").unwrap();
				for (key, class) in entries {
					writeln!(out, "  {key:?}: {class:?},").unwrap();
				}
				out.push_str("} as const;\n");
				writeln!(out, "export type {ty} = keyof typeof {name};").unwrap();
			}
			Ts::Types(decls) =>
				for decl in decls.values() {
					writeln!(out, "{decl}").unwrap();
				},
		}
	}
}

fn literal(v: &Value) -> String {
	match v {
		Value::Array(items) => format!("[{}]", items.iter().map(literal).collect::<Vec<_>>().join(", ")),
		Value::Object(fields) => format!("{{ {} }}", fields.iter().map(|(k, v)| format!("{k:?}: {}", literal(v))).collect::<Vec<_>>().join(", ")),
		scalar => scalar.to_string(),
	}
}
