import { existsSync, readdirSync } from "node:fs";
import { join, relative, sep } from "node:path";

/** Next's app-root metadata routes generated by code, served without an extension. */
const CODE_ROUTES: Readonly<Record<string, string>> = { robots: "/robots.txt", sitemap: "/sitemap.xml", manifest: "/manifest.webmanifest" };
const IMAGE_ROUTE = /^(icon|apple-icon|opengraph-image|twitter-image)\d*$/;
const CODE = /\.(ts|tsx|js|jsx|mjs)$/;
const STATIC = /^(favicon\.ico|robots\.txt|sitemap\.xml|manifest\.(json|webmanifest)|(icon|apple-icon|opengraph-image|twitter-image)\d*\.(ico|jpe?g|png|gif|svg))$/;

/**
 * Every path a brand tree serves outside `[locale]`: `app/`'s route folders
 * (`/og`), its root metadata files (`app/robots.ts` → `/robots.txt`,
 * `app/icon.svg`) and everything under `public/`. A layout, a stylesheet or
 * a route group serves nothing of its own here.
 */
export function servedPaths(root: string): string[] {
  const served: string[] = [];
  const app = join(root, "app");
  for (const entry of existsSync(app) ? readdirSync(app, { withFileTypes: true }) : []) {
    if (entry.isDirectory()) {
      // `[locale]` is the pages; `(group)`, `_private` and `@slot` add no segment.
      if (!/^[[(_@]/.test(entry.name)) served.push(`/${entry.name}`);
      continue;
    }
    if (STATIC.test(entry.name)) {
      served.push(`/${entry.name}`);
      continue;
    }
    if (!CODE.test(entry.name)) continue;
    const base = entry.name.replace(CODE, "");
    const route = CODE_ROUTES[base] ?? (IMAGE_ROUTE.test(base) ? `/${base}` : undefined);
    if (route) served.push(route);
  }
  const pub = join(root, "public");
  for (const entry of existsSync(pub) ? readdirSync(pub, { withFileTypes: true, recursive: true }) : []) {
    if (entry.isFile()) served.push(`/${relative(pub, join(entry.parentPath, entry.name)).split(sep).join("/")}`);
  }
  return served.sort();
}
