use std::collections::BTreeMap;

use ev_lib::ts_gen::Ts;
use serde::Serialize;
use ts_rs::TS;

/// Who.
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd, Serialize, TS)]
#[serde(rename_all = "snake_case")]
enum Role {
	Operator,
	Admin,
}

#[derive(Serialize, TS)]
struct Grant {
	role: Role,
}

#[derive(Serialize, TS)]
struct Caller {
	role: Role,
	grants: Vec<Grant>,
	note: Option<String>,
}

/// A type named twice, by two roots and through a `Vec`, is declared once.
#[test]
fn a_module() {
	let dir = tempfile::tempdir().unwrap();
	let path = dir.path().join("nested/generated.ts");
	let may = BTreeMap::from([(Role::Operator, false), (Role::Admin, true)]);
	Ts::write(
		&path,
		&[
			Ts::types::<(Caller, Grant)>(),
			Ts::Value {
				name: "ROLES",
				value: serde_json::to_value([Role::Operator, Role::Admin]).unwrap(),
			},
			Ts::Value {
				name: "MAY",
				value: serde_json::json!({ "x": may }),
			},
			Ts::Value { name: "N", value: 7.into() },
		],
	);
	assert_eq!(
		std::fs::read_to_string(path).unwrap(),
		r#"// AUTO-GENERATED by `nix run .#gen` — do not edit.

export type Caller = { role: Role, grants: Array<Grant>, note: string | null, };
export type Grant = { role: Role, };
/**
 * Who.
 */
export type Role = "operator" | "admin";

export const ROLES = ["operator", "admin"] as const;

export const MAY = {
  "x": { "admin": true, "operator": false },
} as const;

export const N = 7;
"#
	);
}
