import { defineConfig, devices } from "@playwright/test";

// Capture harness for the uikit gallery. The static board is generated by the
// Rust side into ./dist; this serves that dir and screenshots one primitive per
// page into $EV_SNAPSHOT_OUT. Runner, browsers, fonts and the Tailwind engine
// are pinned together by the flake — see `visual` in flake.nix.
const PORT = 4321;

export default defineConfig({
  testDir: "./",
  fullyParallel: true,
  forbidOnly: true,
  retries: 0,
  reporter: "line",

  use: {
    baseURL: `http://localhost:${PORT}`,
    viewport: { width: 1280, height: 720 },
    deviceScaleFactor: 1,
    colorScheme: "dark",
  },

  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],

  // dist/ must already be generated. This only serves it.
  webServer: {
    command: `python3 -m http.server ${PORT}`,
    cwd: "dist",
    url: `http://localhost:${PORT}/manifest.json`,
    timeout: 30_000,
  },
});
