use dioxus::prelude::*;
use ev::uikit::{
	Alert, AlertDescription, AlertTitle, AlertVariant, Badge, BadgeVariant, Button, ButtonSize, ButtonVariant, Card, CardContent, CardDescription, CardHeader, CardTitle, Separator, Spinner,
	ToastPosition, ToastVariant, Toaster, ToasterProvider, use_toaster,
};

// Generated by the Tailwind CLI from `input.css` (see README); gitignored.
const TAILWIND: Asset = asset!("/assets/tailwind.css");

pub fn run() {
	dioxus::launch(App);
}

#[component]
fn App() -> Element {
	rsx! {
		document::Stylesheet { href: TAILWIND }
		ToasterProvider { Gallery {} }
	}
}

#[component]
fn Gallery() -> Element {
	let toaster = use_toaster();
	let mut position = use_signal(|| ToastPosition::BottomRight);

	let positions = [
		("top-left", ToastPosition::TopLeft),
		("top-center", ToastPosition::TopCenter),
		("top-right", ToastPosition::TopRight),
		("bottom-left", ToastPosition::BottomLeft),
		("bottom-center", ToastPosition::BottomCenter),
		("bottom-right", ToastPosition::BottomRight),
	];

	rsx! {
		div { class: "bg-background text-foreground min-h-dvh",
			div { class: "mx-auto max-w-3xl space-y-12 p-6 sm:p-12",
				header { class: "space-y-2",
					div { class: "flex items-center gap-3",
						h1 { class: "text-2xl font-bold tracking-tight", "ev::uikit" }
						Badge { variant: BadgeVariant::Success, "Dioxus" }
					}
					p { class: "text-muted-foreground text-sm",
						"Live viewer rendered by Dioxus \u{2192} wasm. The React mirror lives in ts/uikit/example."
					}
				}

				Card {
					CardHeader {
						CardTitle { "Toaster" }
						CardDescription { "Enter / exit animate via the shared tokens.css keyframes." }
					}
					CardContent { class: "space-y-4",
						div { class: "flex flex-wrap gap-2",
							Button { size: ButtonSize::Sm, variant: ButtonVariant::Secondary,
								onclick: move |_| { toaster.toast("Default toast"); }, "default" }
							Button { size: ButtonSize::Sm, variant: ButtonVariant::Secondary,
								onclick: move |_| { toaster.success("Success toast"); }, "success" }
							Button { size: ButtonSize::Sm, variant: ButtonVariant::Destructive,
								onclick: move |_| { toaster.error("Error toast"); }, "error" }
							Button { size: ButtonSize::Sm, variant: ButtonVariant::Secondary,
								onclick: move |_| { toaster.info("Info toast"); }, "info" }
							Button { size: ButtonSize::Sm, variant: ButtonVariant::Secondary,
								onclick: move |_| { toaster.warning("Warning toast"); }, "warning" }
							Button { size: ButtonSize::Sm, variant: ButtonVariant::Outline,
								onclick: move |_| { toaster.show("Persistent — won't auto-close", ToastVariant::Default, None); }, "persistent" }
						}
						Separator {}
						div { class: "space-y-2",
							span { class: "text-sm font-medium", "Position" }
							div { class: "flex flex-wrap gap-2",
								for (label , pos) in positions {
									Button {
										key: "{label}",
										size: ButtonSize::Sm,
										variant: if position() == pos { ButtonVariant::Default } else { ButtonVariant::Outline },
										onclick: move |_| position.set(pos),
										"{label}"
									}
								}
							}
						}
					}
				}

				section { class: "space-y-3",
					h2 { class: "text-foreground text-lg font-semibold", "Buttons" }
					div { class: "flex flex-wrap items-center gap-3",
						Button { "Default" }
						Button { variant: ButtonVariant::Secondary, "Secondary" }
						Button { variant: ButtonVariant::Outline, "Outline" }
						Button { variant: ButtonVariant::Ghost, "Ghost" }
						Button { variant: ButtonVariant::Destructive, "Destructive" }
						Button { variant: ButtonVariant::Link, "Link" }
					}
				}

				section { class: "space-y-3",
					h2 { class: "text-foreground text-lg font-semibold", "Badges" }
					div { class: "flex flex-wrap items-center gap-3",
						Badge { "Default" }
						Badge { variant: BadgeVariant::Secondary, "Secondary" }
						Badge { variant: BadgeVariant::Success, "Success" }
						Badge { variant: BadgeVariant::Destructive, "Destructive" }
						Badge { variant: BadgeVariant::Outline, "Outline" }
					}
				}

				section { class: "space-y-3",
					h2 { class: "text-foreground text-lg font-semibold", "Alert" }
					div { class: "flex w-full flex-col gap-3",
						Alert {
							AlertTitle { "Heads up" }
							AlertDescription { "This kit is the source of truth the React port mirrors." }
						}
						Alert { variant: AlertVariant::Destructive,
							AlertTitle { "Something failed" }
							AlertDescription { "Check the console for details." }
						}
					}
				}

				section { class: "space-y-3",
					h2 { class: "text-foreground text-lg font-semibold", "Bits & pieces" }
					div { class: "flex flex-wrap items-center gap-3", Spinner {} }
				}
			}

			Toaster { position: position() }
		}
	}
}
