// `@evinvest/uikit@0.8.1` shipped without `styles/tokens.css`: the file is generated by
// `prepare` into a directory carrying a .gitignore for it, and npm falls back to
// .gitignore when packing. Nothing failed — the tarball was simply built without the
// design tokens, and every consumer importing them broke on install.
//
// The `files` field is a promise about what ships, so it is checked rather than trusted.
// Runs from `prepublishOnly`, which `npm pack` does not trigger, so the nested pack below
// cannot recurse.
import { execFileSync } from "node:child_process";

const REQUIRED = ["package.json", "dist/index.js", "dist/index.d.ts", "styles/tokens.css"];

const out = execFileSync("npm", ["pack", "--dry-run", "--json"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });

// The nested pack re-runs `prepare`, whose bundler chatters on stdout ahead of the JSON,
// so the report is recovered by parsing the last array the output ends with.
function trailingJson(text) {
  for (let i = text.lastIndexOf("["); i >= 0; i = text.lastIndexOf("[", i - 1)) {
    try {
      return JSON.parse(text.slice(i));
    } catch {
      // not the start of the report — keep walking back
    }
  }
  throw new Error(`could not find the pack report in:\n${text}`);
}

const shipped = new Set(trailingJson(out)[0].files.map((f) => f.path));
const missing = REQUIRED.filter((p) => !shipped.has(p));

if (missing.length > 0) {
  console.error(`refusing to publish: the tarball is missing ${missing.join(", ")}`);
  console.error(`it contains: ${[...shipped].sort().join(", ")}`);
  process.exit(1);
}

console.log(`verify-pack: ${REQUIRED.length} required paths present in the tarball`);
