// `@evinvest/uikit@0.8.1` shipped without `styles/tokens.css`: the file was generated by
// `prepare` into a directory carrying a .gitignore for it, and npm falls back to
// .gitignore when packing. Nothing failed — the tarball was simply built without the
// design tokens, and every consumer importing them broke on install. `styles/` is now
// generated by `nix run .#gen` and committed, so nothing there is ignored by either
// tool; this stays as the assertion that the promise still holds.
//
// The `files` field is a promise about what ships, so it is checked rather than trusted.
// Runs from `prepublishOnly`, which `npm pack` does not trigger, so the nested pack below
// cannot recurse.
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { posix } from "node:path";

const REQUIRED = [
  "package.json",
  "dist/index.js",
  "dist/index.d.ts",
  "dist/palette.js",
  "dist/palette.d.ts",
  // the `bin`; it reads `styles/theme.css` beside `dist/` at run time
  "dist/palette-cli.js",
  "styles/tokens.css",
  "styles/theme.css",
  "styles/ev.css",
];

const out = execFileSync("npm", ["pack", "--dry-run", "--json"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });

// The nested pack re-runs `prepare`, whose bundler chatters on stdout ahead of the JSON,
// so the report is recovered by parsing the last array the output ends with.
function trailingJson(text) {
  for (let i = text.lastIndexOf("["); i >= 0; i = text.lastIndexOf("[", i - 1)) {
    try {
      return JSON.parse(text.slice(i));
    } catch {
      // not the start of the report — keep walking back
    }
  }
  throw new Error(`could not find the pack report in:\n${text}`);
}

const shipped = new Set(trailingJson(out)[0].files.map((f) => f.path));
const missing = REQUIRED.filter((p) => !shipped.has(p));

if (missing.length > 0) {
  console.error(`refusing to publish: the tarball is missing ${missing.join(", ")}`);
  console.error(`it contains: ${[...shipped].sort().join(", ")}`);
  process.exit(1);
}

// The kit ships one file per module, so the fixed list above no longer covers
// what a consumer loads. Walk the module graph from the entry through every
// relative import, as the tarball has it: a module `files` or the build left
// out is an import that fails on install, not at publish.
const RELATIVE = /(?:\bfrom\s*|\bimport\s*\(\s*|\bimport\s+)["'](\.{1,2}\/[^"']+)["']/g;
const seen = new Set();
const broken = [];
const queue = ["dist/index.js"];
while (queue.length > 0) {
  const file = queue.pop();
  if (seen.has(file)) continue;
  seen.add(file);
  for (const [, spec] of readFileSync(file, "utf8").matchAll(RELATIVE)) {
    const target = posix.normalize(posix.join(posix.dirname(file), spec));
    if (!shipped.has(target)) broken.push(`${file} → ${spec}`);
    else if (target.endsWith(".js")) queue.push(target);
  }
}
if (broken.length > 0) {
  console.error(`refusing to publish: imports that resolve to nothing in the tarball:\n  ${broken.join("\n  ")}`);
  process.exit(1);
}

console.log(`verify-pack: ${REQUIRED.length} required paths present, ${seen.size} modules reachable from dist/index.js all shipped`);
