/**
 * `evinvest-i18n-slices` — which catalogue keys each part of a Next.js App
 * Router app renders on the client, read off its import graph.
 *
 * A client provider's `messages` are serialised into every page's RSC payload.
 * Slicing is what keeps that to the keys a page can actually ask for: the
 * provider in the root layout carries the {@link MessageSlices.shell}, and each
 * page's `I18nScope` adds its route's slice.
 *
 * The one rule every decision here follows: **a slice may carry a key it does
 * not need, never miss one it does.** A missing key renders English to a reader
 * of another language, silently. So every import is followed (type-only ones
 * excepted), every file below a `"use client"` boundary counts as client, and
 * anything the graph cannot account for — a local import that does not
 * resolve, an `import()` of a computed path, a `t()` with a computed key — is
 * an error rather than a skip.
 *
 * Syntactic, like the extractor: `ts.createSourceFile` per file, no program and
 * no type checker; `paths` come from the app's tsconfig.
 */
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, posix, relative, resolve, sep } from "node:path";

import ts from "typescript";

import type { MessageSlices } from "../slices.js";
import {
  callsIn,
  DEFAULT_EXCLUDE,
  dedupe,
  type Entry,
  flag,
  list,
  literal,
  parse,
  serialise,
  sourceFiles,
  where,
} from "./calls.js";

/**
 * A closed table of copy keyed by an id — `TIP_COPY[anchor](t)` — whose `t()`
 * calls all sit in one module. Followed as an import, that module would put
 * every row in every slice that reaches it. A rule narrows it to the rows whose
 * id appears as a string literal in a file the entry reaches (server or
 * client: a server page passing `anchor="wallet.x"` to a client tip counts).
 *
 * The ids are not listed: they are read back out of the table's own keys
 * through the templates — `tips.*.title` over `tips.wallet.x.title` gives the
 * id `wallet.x`, and the id gives every template's key.
 */
export interface TableRule {
  /** Root-relative path of the module holding the table's `t()` calls. */
  table: string;
  /**
   * Key templates, one `*` each for the id: `["tips.*.title", "tips.*.body"]`.
   * The table's keys that match none stay ordinary keys of the module.
   */
  keys: readonly string[];
  /**
   * Root-relative files whose literals do not count — the module that lists
   * every id (a typed registry of anchors) would otherwise select every row.
   */
  ignore?: readonly string[];
}

/** What {@link messageSlices} reads. */
export interface SliceOptions {
  /** The app's root: where `tsconfig.json` and the app directory are. */
  root: string;
  /** Root-relative App Router directory. Defaults to `app`, else `src/app`. */
  app?: string;
  /** The tsconfig whose `paths` and `baseUrl` resolve aliases. Defaults to `<root>/tsconfig.json` when present. */
  tsconfig?: string;
  /** Names skipped when listing every key for `serverOnly`; as for `collect`. */
  exclude?: readonly string[];
  tables?: readonly TableRule[];
}

/** The slices, plus everything the graph could not account for. */
export interface SliceResult {
  slices: MessageSlices;
  errors: string[];
}

/** The first line of the generated file, as a `"//"` member: JSON has no comments. */
export const SLICES_HEADER =
  "GENERATED by evinvest-i18n-slices from the app's import graph. Do not edit by hand: " +
  "run evinvest-i18n-slices; its --check fails CI when this file drifts from the code.";

/** Files Next renders as a route segment's own — a page, or what wraps or replaces one. */
const ENTRY =
  /^(page|layout|template|loading|error|not-found|forbidden|unauthorized|default|global-error|global-not-found)\.(tsx|ts|jsx|js)$/;
/** Of those, the one a page's `I18nScope` wraps; everything else renders outside it, so it is shell. */
const PAGE = /^page\.(tsx|ts|jsx|js)$/;
/** Parsed and followed; anything else that resolves (CSS, JSON, SVG) is a leaf. */
const CODE = /\.(tsx?|mts|cts|jsx?|mjs|cjs)$/;
/** Tried in this order after the bare path, as `moduleResolution: bundler` does. */
const EXTENSIONS = [".ts", ".tsx", ".mts", ".cts", ".d.ts", ".js", ".jsx", ".mjs", ".cjs"];
/** A `./x.js` specifier in TypeScript source names `./x.ts`. */
const JS_TO_TS: Readonly<Record<string, readonly string[]>> = {
  ".js": [".ts", ".tsx"],
  ".jsx": [".tsx"],
  ".mjs": [".mts"],
  ".cjs": [".cts"],
};

/** One parsed file: what it renders, what it says, whether it starts a client boundary. */
interface Module {
  client: boolean;
  entries: Entry[];
  errors: string[];
  literals: ReadonlySet<string>;
  /** Specifiers with the node they were read at; resolved on first traversal. */
  specifiers: { specifier: string; at: string }[];
}

interface Paths {
  /** Absolute directory `paths` targets are relative to. */
  base: string;
  /** `[prefix, suffix, targets]`, longest prefix first, as tsc tries them. */
  patterns: { prefix: string; suffix: string; wildcard: boolean; targets: string[] }[];
  /** Absolute `baseUrl`, which also resolves bare specifiers. */
  baseUrl: string | null;
}

type Resolution =
  | { kind: "local"; path: string }
  | { kind: "external" }
  | { kind: "unresolved"; alias?: string };

/**
 * Whether a bare specifier can name an npm package. `@/x` (an empty scope),
 * `~/x` and `#x` cannot: they only mean something through an alias — tsconfig
 * `paths`, a bundler alias, package.json `imports` — so one nothing here maps
 * is a local import the graph lost, not a package to stop at.
 */
const couldBePackage = (specifier: string): boolean =>
  specifier.startsWith("@") ? /^@[^/]+\/[^/]/.test(specifier) : !/^[~#]/.test(specifier);

const isFile = (path: string): boolean =>
  statSync(path, { throwIfNoEntry: false })?.isFile() ?? false;

const sortedArray = (keys: Iterable<string>): string[] => [...keys].sort();

/** `"use client"` among the directive prologue — the statements before the first non-string one. */
function startsClientBoundary(source: ts.SourceFile): boolean {
  for (const statement of source.statements) {
    if (!ts.isExpressionStatement(statement) || !ts.isStringLiteral(statement.expression)) return false;
    if (statement.expression.text === "use client") return true;
  }
  return false;
}

/** Runtime imports (static, re-exports, `import()`, `require`) and every string literal. */
function scan(path: string, source: ts.SourceFile): Pick<Module, "errors" | "literals" | "specifiers"> {
  const errors: string[] = [];
  const literals = new Set<string>();
  const specifiers: Module["specifiers"] = [];
  const add = (node: ts.Node, specifier: ts.Node | undefined, what: string) => {
    const text = specifier === undefined ? null : literal(specifier);
    // A computed path could load anything, and its keys would be in no slice.
    if (text === null) errors.push(`${where(path, source, node)}: ${what} of a non-literal path cannot be followed`);
    else specifiers.push({ specifier: text, at: where(path, source, node) });
  };
  const visit = (node: ts.Node) => {
    if (ts.isImportDeclaration(node)) {
      if (node.importClause?.isTypeOnly !== true) add(node, node.moduleSpecifier, "import");
    } else if (ts.isExportDeclaration(node)) {
      if (!node.isTypeOnly && node.moduleSpecifier !== undefined) add(node, node.moduleSpecifier, "export");
    } else if (ts.isImportEqualsDeclaration(node)) {
      if (!node.isTypeOnly && ts.isExternalModuleReference(node.moduleReference))
        add(node, node.moduleReference.expression, "import =");
    } else if (ts.isCallExpression(node)) {
      if (node.expression.kind === ts.SyntaxKind.ImportKeyword) add(node, node.arguments[0], "import()");
      else if (ts.isIdentifier(node.expression) && node.expression.text === "require")
        add(node, node.arguments[0], "require()");
    } else if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
      literals.add(node.text);
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  return { errors, literals, specifiers };
}

/** `paths` and `baseUrl` of one tsconfig, `extends` followed. */
function readPaths(tsconfig: string): Paths {
  const read = ts.readConfigFile(tsconfig, ts.sys.readFile);
  if (read.error !== undefined)
    throw new Error(`${tsconfig}: ${ts.flattenDiagnosticMessageText(read.error.messageText, "\n")}`);
  // Only the options are wanted: listing the project's files would walk the tree for nothing.
  const host: ts.ParseConfigHost = { ...ts.sys, readDirectory: () => [] };
  const { options } = ts.parseJsonConfigFileContent(read.config, host, dirname(tsconfig), undefined, tsconfig);
  // tsc records where an inherited `paths` was declared, which is what its targets are relative to.
  const declaredAt = options["pathsBasePath"];
  const base = options.baseUrl ?? (typeof declaredAt === "string" ? declaredAt : dirname(tsconfig));
  const patterns = Object.entries(options.paths ?? {})
    .map(([pattern, targets]) => {
      const star = pattern.indexOf("*");
      return star === -1
        ? { prefix: pattern, suffix: "", wildcard: false, targets }
        : { prefix: pattern.slice(0, star), suffix: pattern.slice(star + 1), wildcard: true, targets };
    })
    .sort((a, b) => b.prefix.length - a.prefix.length);
  return { base, patterns, baseUrl: options.baseUrl ?? null };
}

function createResolver(root: string, paths: Paths | null) {
  const toRoot = (abs: string) => relative(root, abs).split(sep).join("/");

  const find = (abs: string): string | null => {
    const ext = extname(abs);
    const swapped = (JS_TO_TS[ext] ?? []).map(to => abs.slice(0, -ext.length) + to);
    const candidates = [
      ...swapped,
      abs,
      ...EXTENSIONS.map(e => abs + e),
      ...EXTENSIONS.map(e => join(abs, `index${e}`)),
    ];
    const hit = candidates.find(isFile);
    return hit === undefined ? null : toRoot(hit);
  };

  return (from: string, raw: string): Resolution => {
    // A bundler query (`./icon.svg?url`) names the file before it. A leading `#`
    // is a subpath import (`#components/b`), not a fragment, so it stays.
    const specifier = raw.replace(/(?!^)[?#].*$/, "");
    const local = (abs: string): Resolution => {
      const path = find(abs);
      return path === null ? { kind: "unresolved" } : { kind: "local", path };
    };
    if (/^\.\.?(\/|$)/.test(specifier)) return local(resolve(root, dirname(from), specifier));
    if (specifier.startsWith("/")) return local(specifier);
    if (paths !== null) {
      for (const { prefix, suffix, wildcard, targets } of paths.patterns) {
        const matches = wildcard
          ? specifier.length >= prefix.length + suffix.length &&
            specifier.startsWith(prefix) &&
            specifier.endsWith(suffix)
          : specifier === prefix;
        if (!matches) continue;
        const capture = wildcard ? specifier.slice(prefix.length, specifier.length - suffix.length) : "";
        for (const target of targets) {
          const path = find(resolve(paths.base, target.replace("*", capture)));
          if (path !== null) return { kind: "local", path };
        }
        // A bare `*` maps everything, packages included; anything narrower
        // (`@/*`) is a promise that the specifier is ours, so a miss is a broken import.
        if (prefix !== "" || suffix !== "")
          return { kind: "unresolved" };
      }
      if (paths.baseUrl !== null) {
        const path = find(resolve(paths.baseUrl, specifier));
        if (path !== null) return { kind: "local", path };
      }
    }
    if (!couldBePackage(specifier))
      return {
        kind: "unresolved",
        alias:
          paths === null
            ? "it is an alias, not a package, and no tsconfig was read to map it"
            : "it is an alias, not a package, and the tsconfig's paths do not map it",
      };
    return { kind: "external" };
  };
}

/** Root-relative and POSIX, the shape every path in the result has. */
const normal = (path: string) => posix.normalize(path.split(sep).join("/"));

function appDirectory(root: string, app: string | undefined): string {
  if (app !== undefined) {
    if (!existsSync(join(root, app))) throw new Error(`app directory ${join(root, app)} does not exist`);
    return normal(app);
  }
  const found = ["app", "src/app"].find(dir => existsSync(join(root, dir)));
  if (found === undefined) throw new Error(`no app/ or src/app/ under ${root}; pass the app directory`);
  return found;
}

/** A table rule with its templates applied to the table's keys. */
interface PreparedRule {
  table: string;
  ignore: ReadonlySet<string>;
  /** The table's keys the rule decides; the module's other keys stay ordinary. */
  governed: ReadonlySet<string>;
  byId: ReadonlyMap<string, readonly string[]>;
}

function prepare(rule: TableRule, keys: readonly string[]): PreparedRule | string {
  const templates = rule.keys.map(template => {
    const parts = template.split("*");
    const [prefix, suffix] = parts;
    if (parts.length !== 2 || prefix === undefined || suffix === undefined)
      throw new Error(`table rule for ${rule.table}: key template "${template}" needs exactly one "*"`);
    return { prefix, suffix };
  });
  const governed = new Set<string>();
  const byId = new Map<string, string[]>();
  for (const key of keys) {
    for (const { prefix, suffix } of templates) {
      if (key.length <= prefix.length + suffix.length || !key.startsWith(prefix) || !key.endsWith(suffix))
        continue;
      const id = key.slice(prefix.length, key.length - suffix.length);
      governed.add(key);
      byId.set(id, [...(byId.get(id) ?? []), key]);
    }
  }
  if (governed.size === 0)
    return `table rule for ${rule.table}: none of its t() keys matches ${rule.keys.join(", ")}`;
  return { table: normal(rule.table), ignore: new Set((rule.ignore ?? []).map(normal)), governed, byId };
}

/**
 * Which keys each entry renders on the client.
 *
 * - **Entries** are the App Router's own files under the app directory: every
 *   `page`, and the files that wrap or replace one — `layout`, `template`,
 *   `loading`, `error`, `not-found`, `forbidden`, `unauthorized`, `default`,
 *   `global-error`, `global-not-found`.
 * - **Client** is every file at or below a `"use client"` module on the path
 *   from an entry; its `t()` keys are the slice's.
 * - **`shell`** is every non-page entry's keys together: those render outside
 *   any page's `I18nScope` (a layout around it, an error boundary in its place),
 *   so the provider must carry them.
 * - **`routes`** maps each page to its keys minus the shell's.
 * - **`serverOnly`** is every key under `root` no slice carries.
 *
 * @throws For what the caller has to fix before anything can be read: a missing
 *   app directory or tsconfig, a key template without exactly one `*`.
 */
export function messageSlices(options: SliceOptions): SliceResult {
  const root = resolve(options.root);
  const app = appDirectory(root, options.app);
  const tsconfig = options.tsconfig ?? join(root, "tsconfig.json");
  if (options.tsconfig !== undefined && !existsSync(tsconfig)) throw new Error(`${tsconfig} does not exist`);
  const resolveFrom = createResolver(root, existsSync(tsconfig) ? readPaths(tsconfig) : null);

  const modules = new Map<string, Module>();
  const load = (path: string): Module => {
    const known = modules.get(path);
    if (known !== undefined) return known;
    let module: Module;
    if (!CODE.test(path)) {
      module = { client: false, entries: [], errors: [], literals: new Set(), specifiers: [] };
    } else {
      const source = parse(path, readFileSync(join(root, path), "utf8"));
      const calls = callsIn(path, source);
      const scanned = scan(path, source);
      module = {
        client: startsClientBoundary(source),
        entries: calls.entries,
        errors: [...calls.errors, ...scanned.errors],
        literals: scanned.literals,
        specifiers: scanned.specifiers,
      };
    }
    modules.set(path, module);
    return module;
  };

  const edges = new Map<string, string[]>();
  const graphErrors = new Set<string>();
  const importsOf = (path: string): string[] => {
    const known = edges.get(path);
    if (known !== undefined) return known;
    const found: string[] = [];
    for (const { specifier, at } of load(path).specifiers) {
      const resolution = resolveFrom(path, specifier);
      if (resolution.kind === "local") found.push(resolution.path);
      else if (resolution.kind === "unresolved")
        graphErrors.add(
          `${at}: cannot resolve "${specifier}" — a local import the graph cannot follow` +
            (resolution.alias === undefined ? "" : ` (${resolution.alias})`),
        );
    }
    edges.set(path, found);
    return found;
  };

  /** Everything `starts` load, and the part of it that runs on the client. */
  const reach = (starts: readonly string[]) => {
    const all = new Set<string>();
    const client = new Set<string>();
    const seen = new Set<string>();
    const stack = starts.map(path => ({ path, inClient: false }));
    for (let next = stack.pop(); next !== undefined; next = stack.pop()) {
      const inClient = next.inClient || load(next.path).client;
      const id = `${inClient ? "c" : "s"}:${next.path}`;
      if (seen.has(id)) continue;
      seen.add(id);
      all.add(next.path);
      if (inClient) client.add(next.path);
      for (const path of importsOf(next.path)) stack.push({ path, inClient });
    }
    return { all, client };
  };

  // Every key under the root, read the way `collect` reads it: what no slice
  // carries is `serverOnly`, and an unreadable call anywhere is an error here too.
  const skip = new Set([...DEFAULT_EXCLUDE, ...(options.exclude ?? [])]);
  const listed = [...sourceFiles(root, skip, "")];
  const appFiles = listed.filter(path => path.startsWith(`${app}/`));
  const entries = appFiles.filter(path => ENTRY.test(posix.basename(path))).sort();
  const pages = entries.filter(path => PAGE.test(posix.basename(path)));
  const shellEntries = entries.filter(path => !PAGE.test(posix.basename(path)));

  const ruleErrors: string[] = [];
  const rules: PreparedRule[] = [];
  for (const rule of options.tables ?? []) {
    const table = normal(rule.table);
    if (!isFile(join(root, table))) {
      ruleErrors.push(`table rule: ${table} does not exist under ${root}`);
      continue;
    }
    const prepared = prepare(rule, load(table).entries.map(e => e.key));
    if (typeof prepared === "string") ruleErrors.push(prepared);
    else rules.push(prepared);
  }

  const keysOf = ({ all, client }: { all: ReadonlySet<string>; client: ReadonlySet<string> }) => {
    const keys = new Set<string>();
    for (const path of client) {
      const governed = rules.filter(rule => rule.table === path);
      for (const { key } of load(path).entries)
        if (!governed.some(rule => rule.governed.has(key))) keys.add(key);
    }
    for (const rule of rules) {
      for (const path of all) {
        if (path === rule.table || rule.ignore.has(path)) continue;
        for (const value of load(path).literals) for (const key of rule.byId.get(value) ?? []) keys.add(key);
      }
    }
    return keys;
  };

  const shell = keysOf(reach(shellEntries));
  const routes: Record<string, string[]> = {};
  const carried = new Set(shell);
  for (const page of pages) {
    const own = [...keysOf(reach([page]))].filter(key => !shell.has(key));
    for (const key of own) carried.add(key);
    routes[page] = sortedArray(own);
  }

  for (const path of listed) load(path);
  const everyEntry = [...modules.values()].flatMap(module => module.entries);
  const serverOnly = sortedArray(new Set(everyEntry.map(e => e.key).filter(key => !carried.has(key))));

  const errors = [
    ...ruleErrors,
    ...[...modules.values()].flatMap(module => module.errors),
    ...dedupe(everyEntry).errors,
    ...graphErrors,
  ];
  return {
    slices: { shell: sortedArray(shell), routes, serverOnly },
    errors: [...new Set(errors)].sort(),
  };
}

/** The exact bytes the slices are written as — what `--check` compares against. */
export const serialiseSlices = (slices: MessageSlices): string =>
  serialise({ "//": SLICES_HEADER, ...slices });

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

function strings(value: unknown): string[] | null {
  if (!Array.isArray(value)) return null;
  const found = value.filter((item): item is string => typeof item === "string");
  return found.length === value.length ? found : null;
}

/** `{ "tables": [{ "table", "keys", "ignore"? }] }`, checked field by field. */
function tablesFrom(raw: unknown, path: string): TableRule[] {
  const fail = (what: string) => new Error(`${path}: ${what}`);
  if (!isRecord(raw)) throw fail("expected an object");
  const unknown = Object.keys(raw).filter(key => key !== "tables");
  if (unknown.length > 0) throw fail(`unknown field ${unknown.join(", ")}`);
  const tables = raw["tables"];
  if (tables === undefined) return [];
  if (!Array.isArray(tables)) throw fail(`"tables" must be an array`);
  return tables.map((rule: unknown, at): TableRule => {
    if (!isRecord(rule)) throw fail(`tables[${at}] must be an object`);
    const extra = Object.keys(rule).filter(key => !["table", "keys", "ignore"].includes(key));
    if (extra.length > 0) throw fail(`tables[${at}]: unknown field ${extra.join(", ")}`);
    const table = rule["table"];
    const keys = strings(rule["keys"]);
    const ignore = rule["ignore"] === undefined ? [] : strings(rule["ignore"]);
    if (typeof table !== "string") throw fail(`tables[${at}].table must be a string`);
    if (keys === null || keys.length === 0) throw fail(`tables[${at}].keys must be a non-empty array of strings`);
    if (ignore === null) throw fail(`tables[${at}].ignore must be an array of strings`);
    return { table, keys, ignore };
  });
}

/**
 * `evinvest-i18n-slices` — write the slices, or with `--check` fail when the
 * committed file differs from what the code gives.
 *
 * `--root` (default: the working directory), `--out` (default
 * `<root>/i18n-slices.json`), `--app`, `--tsconfig`, `--exclude a,b`,
 * `--config <json>` for {@link TableRule}s.
 */
export function runSlices(argv: readonly string[]): void {
  const root = flag(argv, "root") ?? process.cwd();
  const out = flag(argv, "out") ?? join(root, "i18n-slices.json");
  const config = flag(argv, "config");
  const app = flag(argv, "app");
  const tsconfig = flag(argv, "tsconfig");
  const tables = config === undefined ? [] : tablesFrom(JSON.parse(readFileSync(config, "utf8")), config);

  const { slices, errors } = messageSlices({
    root,
    exclude: list(flag(argv, "exclude")),
    tables,
    ...(app === undefined ? {} : { app }),
    ...(tsconfig === undefined ? {} : { tsconfig }),
  });
  if (errors.length > 0) {
    console.error(`${errors.length} thing${errors.length === 1 ? "" : "s"} the slice generator cannot account for:\n`);
    for (const error of errors) console.error(`  ${error}`);
    console.error("\nA slice that misses a key renders English to a reader of another language, so these are fatal.");
    process.exit(1);
  }

  const text = serialiseSlices(slices);
  const routes = Object.keys(slices.routes).length;
  if (argv.includes("--check")) {
    if (!existsSync(out) || readFileSync(out, "utf8") !== text) {
      console.error(`${out} is out of date with the code. Run \`evinvest-i18n-slices\`.`);
      process.exit(1);
    }
    console.log(`${out}: up to date (${slices.shell.length} shell keys, ${routes} routes)`);
    return;
  }
  writeFileSync(out, text);
  console.log(
    `${out}: ${slices.shell.length} shell keys, ${routes} routes, ${slices.serverOnly.length} server-only`,
  );
}
